language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
sudo: required
dist: trusty
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.9
   - g++-4.9
   - cmake
   - doxygen
   - python-pip
   - valgrind 
   - ggcov
 coverity_scan:
   project:
     name: "ChaiScript/ChaiScript"
     description: "Build submitted via Travis CI"
   build_command: "cmake --build . -- -j2"

# addons:
#   apt:
#     sources:
#       - llvm-toolchain-precise
#       - ubuntu-toolchain-r-test
#       - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
#     packages:
#       - clang-3.7
#       - g++-5
#       - gcc-5
#       - cmake
#       - cmake-data
before_install:
  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  # - sudo apt-get install -qq cmake doxygen g++-4.9 python-pip valgrind ggcov
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libcppunit-dev
  - sudo pip install cpplint
  - sudo pip install cpp-coveralls
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 80
  # - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - libs/dependencies
script:
  - make codecheck
  - make -j2
  - make test
  - make verify
